name: Meu Workflow Simples
on:
  push:
    branches:
      -main
  jobs:
    build:
      runs-on: ubuntu-lastest
      steps:
        -name: Checkout
        uses: actions/checkout@v2
        run: echo "Hello, World!"
