name: Meu Workflow Simples
on:
    schedule:
        - cron: "5 20 * * *"
jobs:
    build:
      runs-on: ubuntu-lastest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Hello World
          run: echo "Hello, World!"
